name: Tests

on: 
  - push
  - pull_request

jobs:
  tests:
  code_coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
 
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}